baseURL = "https://annzhouccc.github.io/home/"
languageCode = "en-us"
title = "Anchengcheng (Ann) Zhou"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Personal website of Ann Zhou, prospective Computer Science graduate student"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "ann.zhou@wustl.edu"
    linkedin = "https://www.linkedin.com/in/ann-zhou/"
    github = "https://github.com/AnnZhouCcc"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Ann, a Computer Science undergrad from Washington University in St. Louis."
    hero_right = ["**Currently looking for summer research opportunities in summer 2021. Planning to attend graduate school in fall 2022**", 
    "I am a senior undergraduate student, with a major in Computer Science and a minor in Linguistics, from Washington University in St. Louis. Prior to that, I graduated from River Valley High School, Singapore.", 
    "My research interests lie at the intersection of theory and practice. I am excited to work on [algorithm design and analysis when applied to distributed and parallel systems](), or [solve system-related problems from a theoretical standpoint](), be it time complexity or programming model.",
    "I publish under Anchengcheng Zhou."]

[params.process]
    enable = true
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
